In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.full((2, 3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
arr2 = np.full((2,3), False)

In [14]:
for i in range(2):
    for j in range(3):
        print(arr2[i][j])

False
False
False
False
False
False


In [18]:
arr3 = np.array(list(map(lambda x: x[0], arr2)))

In [19]:
arr3

array([False, False])